"""SPARK: Structure-discovered Pairwise Additive Radial-Kinetic GP."""

from gp.spark.model import (
    BayesianRadialFeatureGP,
    PreparedSpark,
    SparkModel,
    fit_spark,
    prepare_spark,
    prepare_spark_from_residualization,
)
from gp.spark.radial import (
    RadialNystromBasis,
    build_state_design,
    nystrom_value_residual_variance,
    pair_geometry,
    pair_indices,
    pair_weights_from_masses,
    pooled_radial_median_scale,
)
from gp.spark.residual import (
    RESIDUALIZATION_ARRAY_FIELDS,
    HamiltonianResidualization,
    PositionResidualBatch,
    PotentialResidualTransform,
    ReconstructedPrediction,
    ReconstructedPredictionSuffix,
    position_residual_inputs,
    position_residual_training,
    prepare_hamiltonian_residualization,
    reconstruct_position_prediction,
    reconstruct_position_prediction_suffix,
    residualization_digest,
    residualization_from_numpy,
    residualization_to_numpy,
)
from gp.spark.structure import (
    DiagonalQuadraticMean,
    HamiltonianSplit,
    fit_diagonal_quadratic_mean,
    infer_hamiltonian_split,
    infer_relative_masses,
)

__all__ = [
    "BayesianRadialFeatureGP",
    "DiagonalQuadraticMean",
    "HamiltonianResidualization",
    "HamiltonianSplit",
    "PotentialResidualTransform",
    "PositionResidualBatch",
    "PreparedSpark",
    "RadialNystromBasis",
    "RESIDUALIZATION_ARRAY_FIELDS",
    "ReconstructedPrediction",
    "ReconstructedPredictionSuffix",
    "SparkModel",
    "build_state_design",
    "fit_diagonal_quadratic_mean",
    "fit_spark",
    "infer_hamiltonian_split",
    "infer_relative_masses",
    "nystrom_value_residual_variance",
    "pair_geometry",
    "pair_indices",
    "pair_weights_from_masses",
    "pooled_radial_median_scale",
    "position_residual_inputs",
    "position_residual_training",
    "prepare_hamiltonian_residualization",
    "prepare_spark",
    "prepare_spark_from_residualization",
    "reconstruct_position_prediction",
    "reconstruct_position_prediction_suffix",
    "residualization_digest",
    "residualization_from_numpy",
    "residualization_to_numpy",
]
